#undef PRODUCT
#define PRODUCT Tanuki by NR

#undef RGBLED_NUM
#define RGBLED_NUM 17
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_TWINKLE
#define RGBLIGHT_EFFECT_TWINKLE_LIFE 35
