#include "config_common.h"

#define GRAVE_ESC_CTRL_OVERRIDE
#define FORCE_NKRO
#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 350
//#define PERMISSIVE_HOLD
#define TAPPING_TERM 300
#define TAPPING_TOGGLE 3
//#define IGNORE_MOD_TAP_INTERRUPT
#define COMBO_COUNT 2
#define COMBO_TERM 25
/* Bootmagic Lite key configuration */
#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 0
//Mouse config
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_TIME_TO_MAX 100

#ifdef RGBLIGHT_ENABLE
//#undef RGBLED_NUM
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
//#define RGBLIGHT_EFFECT_ALTERNATING
//#define RGBLIGHT_EFFECT_BREATHE_CENTER 2.7
//#define RGBLIGHT_SLEEP
#define RGBLIGHT_HUE_STEP 15
//#define RGBLIGHT_SAT_STEP 8
//#define RGBLIGHT_VAL_STEP 8
#endif

#ifdef BACKLIGHT_ENABLE
#define BACKLIGHT_BREATHING
#define BACKLIGHT_LEVELS 5
#endif

#undef NO_ACTION_ONESHOT
#undef NO_ACTION_LAYER
#undef NO_ACTION_TAPPING
//#define NO_ACTION_ONESHOT
//#define NO_ACTION_MACRO
//#define NO_ACTION_FUNCTION


