#undef PRODUCT
#define PRODUCT Corne by NR
//#undef RGBLIGHT_EFFECT_BREATHING
//#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
//#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
//ok	#undef DISABLE_RGB_MATRIX_ALPHAS_MODS
//	#undef DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
//	#undef DISABLE_RGB_MATRIX_BREATHING
//	#undef DISABLE_RGB_MATRIX_BAND_SAT
//ok	#undef DISABLE_RGB_MATRIX_BAND_VAL
	#undef DISABLE_RGB_MATRIX_BAND_VAL
//	#undef DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
//ok	#undef DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
	#undef DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
//	#undef DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
//	#undef DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
//ok	#undef DISABLE_RGB_MATRIX_CYCLE_ALL
//ok	#undef DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
//ok	#undef DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
	#undef DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
//	#undef DISABLE_RGB_MATRIX_CYCLE_OUT_IN
//	#undef DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
//ok	#undef DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON 
	#undef DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON 
//	#undef DISABLE_RGB_MATRIX_DUAL_BEACON
//ok	#undef DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
	#undef DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
//	#undef DISABLE_RGB_MATRIX_CYCLE_SPIRAL
//	#undef DISABLE_RGB_MATRIX_RAINBOW_BEACON
//	#undef DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
//	#undef DISABLE_RGB_MATRIX_RAINDROPS
//	#undef DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
//	#undef DISABLE_RGB_MATRIX_TYPING_HEATMAP
